// #65L slice 3 — C++ parity comparator for RF-DETR backbone.
//
// Loads the per-stage Python reference dumps generated by
// `/tmp/yolocpp_parity/dump_rfdetr_forward.py` (env-gated via
// `RFDETR_PARITY_DUMP_DIR=/tmp/yolocpp_parity/dumps/rfdetr_base`),
// runs the C++ backbone forward with the same `rf-detr-base.pth`
// weights on the same input, and reports per-stage max-absolute-diff.
//
// Bisects the architecture: the FIRST stage with non-trivial diff
// is the next parity bug to chase. SKIP-gated when the dump
// directory is absent.

#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

#include <torch/torch.h>

#include "yolocpp/models/rfdetr.hpp"
#include "yolocpp/models/rfdetr_backbone.hpp"
#include "yolocpp/models/rfdetr_projector.hpp"
#include "yolocpp/serialization/pt_loader.hpp"
#include "yolocpp/serialization/rfdetr_weights.hpp"

namespace fs = std::filesystem;

namespace {

torch::Tensor load_dump(const fs::path& dir, const std::string& name) {
  fs::path bin = dir / (name + ".bin");
  fs::path shape_p = dir / (name + ".shape");
  if (!fs::exists(bin) || !fs::exists(shape_p)) return {};
  std::ifstream f_shape(shape_p);
  std::stringstream ss; ss << f_shape.rdbuf();
  std::vector<int64_t> shape;
  int64_t v; while (ss >> v) shape.push_back(v);
  int64_t numel = 1;
  for (auto s : shape) numel *= s;
  std::vector<float> buf(numel);
  std::ifstream f_bin(bin, std::ios::binary);
  f_bin.read(reinterpret_cast<char*>(buf.data()), numel * sizeof(float));
  auto t = torch::from_blob(buf.data(), shape, torch::kFloat).clone();
  return t;
}

float max_abs_diff(const torch::Tensor& a, const torch::Tensor& b) {
  if (a.sizes() != b.sizes()) return std::numeric_limits<float>::infinity();
  return (a - b).abs().max().item<float>();
}

}  // namespace

int main() {
  const char* dir = std::getenv("RFDETR_PARITY_DUMP_DIR");
  if (!dir || !fs::is_directory(dir)) {
    std::cout << "SKIP: RFDETR_PARITY_DUMP_DIR not set or not a directory\n";
    return 0;
  }
  fs::path d(dir);
  auto inp = load_dump(d, "input");
  if (!inp.defined()) {
    std::cout << "SKIP: input.bin missing in " << dir << "\n";
    return 0;
  }
  std::cout << "input shape: " << inp.sizes() << "\n";

  // Build base model + load weights.
  yolocpp::models::RFDetr m(yolocpp::models::kRfdetrBase, /*nc=*/80);
  m->eval();
  const char* w = std::getenv("RFDETR_TEST_WEIGHTS_DIR");
  if (!w) {
    std::cout << "SKIP: RFDETR_TEST_WEIGHTS_DIR not set\n";
    return 0;
  }
  fs::path wpath = fs::path(w) / "rf-detr-base.pth";
  if (!fs::exists(wpath)) {
    std::cout << "SKIP: " << wpath << " missing\n";
    return 0;
  }
  m->load_from_upstream_pt(wpath.string(), /*strict=*/false);

  // Walk the live module tree to find the inner Dinov2Model so we
  // can call `embeddings()` and `encoder.forward_all_blocks()`
  // directly — bypassing forward_eval to capture per-stage
  // activations alongside Python's dumps.
  torch::NoGradGuard ng;
  auto& slot = *m->named_children()["backbone"]->as<torch::nn::ModuleListImpl>();
  auto& bs   = *slot[0]->as<yolocpp::models::rfdetr::BackboneSlotImpl>();
  auto& wrapper = *bs.encoder.ptr();          // Dinov2Wrapper
  auto& dmodel  = *wrapper.encoder.ptr();     // Dinov2Model

  // Sanity: verify position_embeddings parameter (the source of the
  // 0.0063 diff) is bit-equal to what `load_flat_state_dict` sees.
  {
    auto sd = yolocpp::serialization::load_flat_state_dict(
        wpath.string(), "model");
    for (auto& [k, t] : sd.entries) {
      if (k == "backbone.0.encoder.encoder.embeddings.position_embeddings") {
        float diff = max_abs_diff(
            dmodel.embeddings->position_embeddings.to(torch::kFloat).contiguous(),
            t.to(torch::kFloat).contiguous());
        std::cout << "[probe] position_embeddings  shape="
                  << dmodel.embeddings->position_embeddings.sizes()
                  << "  loaded_max_abs_diff=" << diff << "\n";
        break;
      }
    }
  }

  // Embeddings sub-stage bisection.
  auto stages = dmodel.embeddings->forward_stages(inp);
  auto report_stage = [&](const std::string& name, const torch::Tensor& cpp_t) {
    auto py_t = load_dump(d, name);
    if (!py_t.defined()) {
      std::cout << "[stage] " << name << "  C++ shape=" << cpp_t.sizes()
                << "  (no Py dump)\n";
      return;
    }
    float diff = max_abs_diff(cpp_t.to(torch::kFloat).contiguous(),
                                py_t.to(torch::kFloat).contiguous());
    std::cout << "[stage] " << std::left << name
              << "  shape=" << cpp_t.sizes()
              << "  max_abs_diff=" << diff << "\n";
  };
  report_stage("emb_step1_patch",     stages.patch);
  report_stage("emb_step2_with_cls",  stages.with_cls);
  report_stage("emb_step3_pos_embed", stages.pos_embed);
  report_stage("emb_step4_with_pos",  stages.with_pos);
  report_stage("embeddings_out",      stages.windowed);
  auto emb_cpp = stages.windowed;

  auto blocks = dmodel.encoder->forward_all_blocks(emb_cpp);
  for (size_t i = 0; i < blocks.size(); ++i) {
    char name[32]; std::snprintf(name, sizeof(name), "layer%02zu_out", i);
    auto py = load_dump(d, name);
    if (!py.defined()) continue;
    float diff = max_abs_diff(blocks[i].to(torch::kFloat).contiguous(),
                                py.to(torch::kFloat).contiguous());
    std::cout << "[stage] " << name << "  shape="
              << blocks[i].sizes() << "  max_abs_diff=" << diff << "\n";
  }

  return 0;
}
