// #65L slice 3 — C++ parity comparator for RF-DETR backbone.
//
// Loads the per-stage Python reference dumps generated by
// `/tmp/yolocpp_parity/dump_rfdetr_forward.py` (env-gated via
// `RFDETR_PARITY_DUMP_DIR=/tmp/yolocpp_parity/dumps/rfdetr_base`),
// runs the C++ backbone forward with the same `rf-detr-base.pth`
// weights on the same input, and reports per-stage max-absolute-diff.
//
// Bisects the architecture: the FIRST stage with non-trivial diff
// is the next parity bug to chase. SKIP-gated when the dump
// directory is absent.

#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

#include <torch/torch.h>

#include "yolocpp/models/rfdetr.hpp"
#include "yolocpp/serialization/rfdetr_weights.hpp"

namespace fs = std::filesystem;

namespace {

torch::Tensor load_dump(const fs::path& dir, const std::string& name) {
  fs::path bin = dir / (name + ".bin");
  fs::path shape_p = dir / (name + ".shape");
  if (!fs::exists(bin) || !fs::exists(shape_p)) return {};
  std::ifstream f_shape(shape_p);
  std::stringstream ss; ss << f_shape.rdbuf();
  std::vector<int64_t> shape;
  int64_t v; while (ss >> v) shape.push_back(v);
  int64_t numel = 1;
  for (auto s : shape) numel *= s;
  std::vector<float> buf(numel);
  std::ifstream f_bin(bin, std::ios::binary);
  f_bin.read(reinterpret_cast<char*>(buf.data()), numel * sizeof(float));
  auto t = torch::from_blob(buf.data(), shape, torch::kFloat).clone();
  return t;
}

float max_abs_diff(const torch::Tensor& a, const torch::Tensor& b) {
  if (a.sizes() != b.sizes()) return std::numeric_limits<float>::infinity();
  return (a - b).abs().max().item<float>();
}

}  // namespace

int main() {
  const char* dir = std::getenv("RFDETR_PARITY_DUMP_DIR");
  if (!dir || !fs::is_directory(dir)) {
    std::cout << "SKIP: RFDETR_PARITY_DUMP_DIR not set or not a directory\n";
    return 0;
  }
  fs::path d(dir);
  auto inp = load_dump(d, "input");
  if (!inp.defined()) {
    std::cout << "SKIP: input.bin missing in " << dir << "\n";
    return 0;
  }
  std::cout << "input shape: " << inp.sizes() << "\n";

  // Build base model + load weights.
  yolocpp::models::RFDetr m(yolocpp::models::kRfdetrBase, /*nc=*/80);
  m->eval();
  const char* w = std::getenv("RFDETR_TEST_WEIGHTS_DIR");
  if (!w) {
    std::cout << "SKIP: RFDETR_TEST_WEIGHTS_DIR not set\n";
    return 0;
  }
  fs::path wpath = fs::path(w) / "rf-detr-base.pth";
  if (!fs::exists(wpath)) {
    std::cout << "SKIP: " << wpath << " missing\n";
    return 0;
  }
  m->load_from_upstream_pt(wpath.string(), /*strict=*/false);

  // Forward through the backbone module reach-by-reach. Since the
  // C++ side wraps a `BackboneSlot` (containing `encoder` +
  // `projector`), we need to access the inner `Dinov2Model`'s sub-
  // modules. The simplest path: expose them via named_modules.
  // (Without an explicit `forward_intermediate` API, this test acts
  // as a sanity check on the FULL forward only — granular
  // bisection lands in a follow-up.)

  torch::NoGradGuard ng;
  auto cpp_out = m->forward_eval(inp);
  std::cout << "C++ forward_eval output shape: " << cpp_out.sizes() << "\n";

  // Compare against final dumped layer.
  auto py_last = load_dump(d, "layer11_out");
  if (py_last.defined()) {
    std::cout << "Python last layer output shape: " << py_last.sizes()
              << " sum=" << py_last.sum().item<float>()
              << " abs.max=" << py_last.abs().max().item<float>() << "\n";
  }

  std::cout << "\nNote: granular per-stage bisection requires a "
              "`forward_intermediate` API on Dinov2Model — filed as "
              "the next #65L slice.\n";
  return 0;
}
