#!/usr/bin/env bash
# #60C — release/publish pipeline for the trained (version × scale × task)
# weight matrix produced by scripts/train_matrix.sh.
#
# Reads runs/matrix/results.csv, stages each successful cell's checkpoint under
# the canonical published name (yolo<N><scale>[-seg|-pose|-obb|-cls].pt — no `v`,
# per CLAUDE.md), writes a RELEASE.md manifest table (name / version / scale /
# task / metric / size / epochs), and — only when explicitly asked — uploads the
# staged files to a GitHub Release via `gh`.
#
# SAFE BY DEFAULT: with no flags it is a DRY RUN (prints the plan, touches
# nothing). `--stage` copies + writes the manifest; `--upload` additionally runs
# `gh release upload`. The maintainer runs `--upload` by hand — this script
# never pushes on its own.
#
# Usage:
#   scripts/publish_weights.sh                      # dry-run plan
#   scripts/publish_weights.sh --stage              # copy → runs/release/ + RELEASE.md
#   scripts/publish_weights.sh --upload --tag wX    # stage, then gh release upload
#   scripts/publish_weights.sh --out runs/matrix --release-dir runs/release

set -u
cd "$(dirname "$0")/.."

OUT="runs/matrix"
REL="runs/release"
TAG=""
MODE="dryrun"          # dryrun | stage | upload

while [ $# -gt 0 ]; do
  case "$1" in
    --out)         OUT="$2"; shift 2 ;;
    --release-dir) REL="$2"; shift 2 ;;
    --tag)         TAG="$2"; shift 2 ;;
    --stage)       MODE="stage"; shift ;;
    --upload)      MODE="upload"; shift ;;
    -h|--help)     grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "[error] unknown arg: $1" >&2; exit 2 ;;
  esac
done

RESULTS="$OUT/results.csv"
if [ ! -f "$RESULTS" ]; then
  echo "[error] no results CSV at $RESULTS — run scripts/train_matrix.sh first" >&2
  exit 2
fi

# Default tag: weights-v<VERSION> (read through the single source of truth).
[ -z "$TAG" ] && TAG="weights-v$(cat VERSION 2>/dev/null | tr -d '[:space:]')"

# Supported version set (closed) — guards against a malformed cell name.
is_supported_version() {
  case "$1" in
    1|2|3|4|5|6|7|8|9|10|11|12|13|26) return 0 ;;
    *) return 1 ;;
  esac
}

# cell "v8n_segment" → canonical "yolo8n-seg" (no extension, no `v`).
canonical_name() {
  local cell="$1" head task ver scale suffix
  head="${cell%%_*}"          # v8n
  task="${cell#*_}"           # segment
  # split head into v<digits><scaleletter>
  if [[ "$head" =~ ^v([0-9]+)([nsmlx])$ ]]; then
    ver="${BASH_REMATCH[1]}"; scale="${BASH_REMATCH[2]}"
  else
    echo ""; return 1
  fi
  is_supported_version "$ver" || { echo ""; return 1; }
  case "$task" in
    detect)   suffix="" ;;
    classify) suffix="-cls" ;;
    segment)  suffix="-seg" ;;
    pose)     suffix="-pose" ;;
    obb)      suffix="-obb" ;;
    *) echo ""; return 1 ;;
  esac
  echo "yolo${ver}${scale}${suffix}"
}

human_size() { [ -f "$1" ] && du -h "$1" | cut -f1 || echo "-"; }

# ── walk the results CSV ────────────────────────────────────────────────────
n_ok=0; n_skip=0; declare -a PLAN_NAME PLAN_SRC PLAN_META

# CSV columns: cell,task,scale,init,data,epochs,status,metric,seconds,artifact
{
  read -r _header  # discard header
  while IFS=, read -r cell task scale init data epochs status metric seconds artifact; do
    [ -z "${cell// /}" ] && continue
    if [ "$status" != "ok" ]; then
      echo "[skip] $cell — status=$status"; n_skip=$((n_skip+1)); continue
    fi
    if [ ! -f "$artifact" ]; then
      echo "[skip] $cell — artifact missing ($artifact)"; n_skip=$((n_skip+1)); continue
    fi
    name="$(canonical_name "$cell")"
    if [ -z "$name" ]; then
      echo "[skip] $cell — could not derive canonical name"; n_skip=$((n_skip+1)); continue
    fi
    PLAN_NAME+=( "$name.pt" )
    PLAN_SRC+=( "$artifact" )
    PLAN_META+=( "${cell}|${task}|${scale}|${metric:-NA}|${epochs}|$(human_size "$artifact")" )
    n_ok=$((n_ok+1))
  done
} < "$RESULTS"

echo
echo "Release tag : $TAG"
echo "Stage dir   : $REL"
echo "Publishable : $n_ok cell(s)   (skipped $n_skip)"
echo "Mode        : $MODE"
echo

if [ "$n_ok" -eq 0 ]; then
  echo "[done] nothing to publish."
  exit 0
fi

printf '  %-22s  %-10s  %-7s  %-8s  %s\n' "published.pt" "task" "metric" "size" "← source"
for i in "${!PLAN_NAME[@]}"; do
  IFS='|' read -r cell task scale metric epochs sz <<< "${PLAN_META[$i]}"
  printf '  %-22s  %-10s  %-7s  %-8s  %s\n' "${PLAN_NAME[$i]}" "$task" "$metric" "$sz" "${PLAN_SRC[$i]}"
done

if [ "$MODE" = "dryrun" ]; then
  echo
  echo "[dry-run] nothing copied. Re-run with --stage to materialise $REL/,"
  echo "          or --upload --tag <tag> to also push to the GitHub Release."
  exit 0
fi

# ── stage: copy → REL/ under canonical names + write RELEASE.md ──────────────
mkdir -p "$REL"
MAN="$REL/RELEASE.md"
{
  echo "# yolocpp trained weight matrix — \`$TAG\`"
  echo
  echo "Generated by \`scripts/publish_weights.sh\` from \`$RESULTS\`."
  echo "Canonical names follow the \`yolo<N><scale>[-task]\` convention (no \`v\`)."
  echo
  echo "| weight | version | scale | task | metric | epochs | size |"
  echo "|--------|---------|-------|------|--------|--------|------|"
} > "$MAN"

for i in "${!PLAN_NAME[@]}"; do
  cp -f "${PLAN_SRC[$i]}" "$REL/${PLAN_NAME[$i]}"
  IFS='|' read -r cell task scale metric epochs sz <<< "${PLAN_META[$i]}"
  ver="${cell%%_*}"; ver="${ver#v}"; ver="${ver%[nsmlx]}"
  echo "| \`${PLAN_NAME[$i]}\` | yolo${ver} | $scale | $task | $metric | $epochs | $sz |" >> "$MAN"
done

echo
echo "[stage] copied $n_ok weight(s) → $REL/ and wrote $MAN"

if [ "$MODE" = "stage" ]; then
  echo "[stage] done. Inspect $REL/, then run with --upload --tag $TAG to publish."
  exit 0
fi

# ── upload: gh release upload (maintainer-invoked) ──────────────────────────
if ! command -v gh >/dev/null 2>&1; then
  echo "[error] gh CLI not found — install it or upload $REL/ by hand." >&2
  exit 1
fi
echo "[upload] gh release upload $TAG $REL/*.pt $MAN --clobber"
gh release view "$TAG" >/dev/null 2>&1 || gh release create "$TAG" \
  --title "Trained weights $TAG" --notes-file "$MAN" || {
    echo "[error] could not create/find release $TAG" >&2; exit 1; }
gh release upload "$TAG" "$REL"/*.pt "$MAN" --clobber || {
  echo "[error] gh release upload failed" >&2; exit 1; }
echo "[upload] published $n_ok weight(s) to release $TAG"
